from litgen.internal.function_adapt._function_adapt import CppFunctionDeclWithAdaptedParams, LambdaAdapter
from litgen.internal.function_adapt.function_params_adapter import make_function_params_adapter
