from skbuild import setup  # This line replaces 'from setuptools import setup'
# from setuptools import setup

setup(
    name='litgensample',
    version='0.1.0',
    author='Pascal Thomet',
    author_email='pthomet@gmail.com',
    description='litgensample, example library generated by litgen (a pybind11 automated generator)',
    url='https://github.com/pthom/pybind11_literate_generator',

    packages=(["litgensample"]),
    package_dir={"": "binding_module"},
    cmake_install_dir="binding_module/litgensample",
    include_package_data=True,
    extras_require={"test": ["pytest"]},
    python_requires=">=3.6",
    package_data={"litgensample": ["*.pyi"]}
)
