#pragma once
#include "api_marker.h"

#include "mylib/_bind_type.h"
#include "mylib/basic_test.h"
#include "mylib/header_filter_test.h"
#include "mylib/c_style_array_test.h"
#include "mylib/c_style_buffer_to_pyarray_test.h"
#include "mylib/c_string_list_test.h"
#include "mylib/modifiable_immutable_test.h"
#include "mylib/overload_test.h"
#include "mylib/enum_test.h"
#include "mylib/class_test.h"
#include "mylib/class_inheritance_test.h"
#include "mylib/class_adapt_test.h"
#include "mylib/class_copy_test.h"
#include "mylib/class_virtual_test.h"
#include "mylib/return_value_policy_test.h"
#include "mylib/inner_class_test.h"
#include "mylib/mix_adapters_class_test.h"
#include "mylib/namespace_test.h"
#include "mylib/operators.h"
#include "mylib/call_policies_test.h"
#include "mylib/qualified_scoping_test.h"
#include "mylib/template_function_test.h"
#include "mylib/template_class_test.h"
#include "mylib/c_extern_c.h"
#include "mylib/class_default_ctor_test.h"
#include "mylib/smart_ptr.h"
//#include "mylib/sandbox.h"

// brace_init_default_value.h must be included last (see explanation inside test_change_decl_stmt_to_function_decl_if_suspicious)
#include "mylib/brace_init_default_value.h"
