import numpy

# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# <autogen:pyi> // Autogenerated code below! Do not edit!

# <namespace LiterateGeneratorExample>


class MyEnum(Enum):    # example_library/litgensample.h:23
    """A super nice enum
    for demo purposes ( bool val = True )
    """
    a = 1   # This is value a
    aa = 2  # this is value aa
    aaa = 3 # this is value aaa
    
    # Lonely comment
    
    # This is value b
    b = 4
    
    # This is c
    # with doc on several lines
    c = a | b
    

# </namespace LiterateGeneratorExample>

# </autogen:pyi>
