// ============================================================================
// This file was autogenerated
// It is presented side to side with its source: class_test.h
// It is not used in the compilation
//    (see integration_tests/bindings/pybind_mylib.cpp which contains the full binding
//     code, including this code)
// ============================================================================

#include <nanobind/nanobind.h>
#include <nanobind/stl/string.h>
#include <nanobind/stl/function.h>
#include "mylib_main/mylib.h"

namespace py = nanobind;

// <litgen_glue_code>  // Autogenerated code below! Do not edit!

// </litgen_glue_code> // Autogenerated code end


void py_init_module_mylib(py::module_& m)
{
    // <litgen_pydef> // Autogenerated code below! Do not edit!
    ////////////////////    <generated_from:class_test.h>    ////////////////////
    auto pyClassMyClass =
        nb::class_<MyClass>
            (m, "MyClass", "This is the class doc. It will be published as MyClass.__doc__")
        .def(nb::init<int, const std::string &>(),
            nb::arg("factor") = 10, nb::arg("message") = "hello")
        .def_rw("factor", &MyClass::factor, "")
        .def_rw("delta", &MyClass::delta, "")
        .def_rw("message", &MyClass::message, "")
        .def_rw("numbers", &MyClass::numbers, " By default, modifications from python are not propagated to C++ for stl containers\n (see https://pybind11.readthedocs.io/en/stable/advanced/cast/stl.html)")
        .def("append_number_from_cpp",
            &MyClass::append_number_from_cpp,
            nb::arg("v"),
            "However you can call dedicated modifying methods")
        .def_prop_ro("values",
            [](MyClass &self) -> nb::ndarray<int, nb::numpy, nb::shape<2>, nb::c_contig>
            {
                return self.values;
            },
            "")
        .def_prop_ro("flags",
            [](MyClass &self) -> nb::ndarray<bool, nb::numpy, nb::shape<3>, nb::c_contig>
            {
                return self.flags;
            },
            "")
        .def_ro_static("const_static_value", &MyClass::const_static_value, "")
        .def_rw_static("static_value", &MyClass::static_value, "")
        .def("calc",
            &MyClass::calc,
            nb::arg("x"),
            "calc: example of simple method")
        .def("set_message",
            &MyClass::set_message,
            nb::arg("m"),
            "set_message: another example of simple method")
        .def_static("static_message",
            &MyClass::static_message, "Returns a static message")
        ;


    auto pyClassMySingletonClass =
        nb::class_<MySingletonClass>
            (m, "MySingletonClass", " MySingletonClass: demonstrate how to instantiate a singleton\n - The instance method shall return with return_value_policy::reference\n - The destructor may be private")
        .def_rw("value", &MySingletonClass::value, "")
        .def(nb::init<>())
        .def_static("instance",
            &MySingletonClass::instance,
            "see: options.fn_return_force_policy_reference_for_references__regex = r\"instance\"",
            nb::rv_policy::reference)
        ;


    auto pyClassMyFinalClass =
        nb::class_<MyFinalClass>
            (m, "MyFinalClass", nb::is_final(), " This struct is final, and thus cannot be inherited from python\n(final class)")
        .def(nb::init<>()) // implicit default constructor
        .def("foo",
            &MyFinalClass::foo)
        ;


    auto pyClassMyStructDynamic =
        nb::class_<MyStructDynamic>
            (m, "MyStructDynamic", nb::dynamic_attr(), " This class accepts dynamic attributes\n see autogenerate_mylib.py:\n     options.class_dynamic_attributes__regex = r\"Dynamic$\"")
        .def("__init__", [](MyStructDynamic * self, int cpp_member = 1)
        {
            new (self) MyStructDynamic();  // placement new
            auto r_ctor_ = self;
            r_ctor_->cpp_member = cpp_member;
        },
        nb::arg("cpp_member") = 1
        )
        .def_rw("cpp_member", &MyStructDynamic::cpp_member, "")
        ;


    auto pyClassMyStructWithNestedEnum =
        nb::class_<MyStructWithNestedEnum>
            (m, "MyStructWithNestedEnum", "");

    { // inner classes & enums of MyStructWithNestedEnum
        auto pyEnumChoice =
            nb::enum_<MyStructWithNestedEnum::Choice>(pyClassMyStructWithNestedEnum, "Choice", nb::is_arithmetic(), "")
                .value("a", MyStructWithNestedEnum::Choice::A, "");
    } // end of inner classes & enums of MyStructWithNestedEnum

    pyClassMyStructWithNestedEnum
        .def(nb::init<>()) // implicit default constructor
        .def("handle_choice",
            &MyStructWithNestedEnum::HandleChoice,
            nb::arg("value") = MyStructWithNestedEnum::Choice::A,
            " The first param of this function uses the inner scope of this class!\n When building the bindings, we need to add MyStructWithNestedEnum::")
        ;


    auto pyClassClassWithInlineForwardDeclaredMethod =
        nb::class_<ClassWithInlineForwardDeclaredMethod>
            (m, "ClassWithInlineForwardDeclaredMethod", "")
        .def(nb::init<>()) // implicit default constructor
        .def("get_tex_id",
            &ClassWithInlineForwardDeclaredMethod::GetTexID)
        ;
    ////////////////////    </generated_from:class_test.h>    ////////////////////

    // </litgen_pydef> // Autogenerated code end
}
