// ============================================================================
// This file was autogenerated
// It is presented side to side with its source: header_filter_test.h
// It is not used in the compilation
//    (see integration_tests/bindings/pybind_mylib.cpp which contains the full binding
//     code, including this code)
// ============================================================================

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/functional.h>
#include <pybind11/numpy.h>
#include "mylib/mylib_main/mylib.h"

namespace py = pybind11;

// <litgen_glue_code>  // Autogenerated code below! Do not edit!

// </litgen_glue_code> // Autogenerated code end


void py_init_module_mylib(py::module& m)
{
    // <litgen_pydef> // Autogenerated code below! Do not edit!
    ////////////////////    <generated_from:header_filter_test.h>    ////////////////////
    // #if HEADER_FILTER_ACCEPTABLE_IF
    //

    m.def("filter_acceptable_if_function",
        FilterAcceptableIfFunction);
    // #endif
    //
    // #if defined(HEADER_FILTER_ACCEPTABLE_IF)
    //

    m.def("filter_acceptable_defined_function",
        FilterAcceptableDefinedFunction);
    // #endif
    //
    // #if HEADER_FILTER_ACCEPTABLE_IF
    //

    m.def("else_branch_primary",
        ElseBranchPrimary);
    // #else
    //
    // #endif
    //
    ////////////////////    </generated_from:header_filter_test.h>    ////////////////////

    // </litgen_pydef> // Autogenerated code end
}
