# ============================================================================
# This file was autogenerated
# It is presented side to side with its source: header_filter_test.h
#    (see integration_tests/bindings/lg_mylib/__init__pyi which contains the full
#     stub code, including this code)
# ============================================================================

# type: ignore

# <litgen_stub> // Autogenerated code below! Do not edit!
####################    <generated_from:header_filter_test.h>    ####################

# Here, we test that functions placed under unknown preprocessor conditions are not exported by default
# You could choose to add them anyway with:
#    options.srcmlcpp_options.header_filter_acceptable_suffixes += "|OBSCURE_OPTION"

# The same filtering also applies to `#if` conditions (not only `#ifdef`/`#ifndef`):
# the macro name referenced in the condition is matched against
# options.srcmlcpp_options.header_filter_acceptable__regex, exactly like `#ifdef`.

# OBSCURE_OPTION is not acceptable => this function is not exported

# #if HEADER_FILTER_ACCEPTABLE_IF
#
def filter_acceptable_if_function() -> int:
    pass

# #endif
#

# #if defined(HEADER_FILTER_ACCEPTABLE_IF)
#
def filter_acceptable_defined_function() -> int:
    pass

# #endif
#

# The `#else` branch of an accepted region is inactive: only the primary branch is
# exported (the `#else` body is dropped). Since HEADER_FILTER_ACCEPTABLE_IF is defined,
# the primary branch is what the C++ compiler keeps too.
# #if HEADER_FILTER_ACCEPTABLE_IF
#
def else_branch_primary() -> int:
    pass

# #else
#
# #endif
#
####################    </generated_from:header_filter_test.h>    ####################

# </litgen_stub> // Autogenerated code end!
