# ============================================================================
# This file was autogenerated
# It is presented side to side with its source: namespace_test.h
#    (see integration_tests/bindings/lg_mylib/__init__pyi which contains the full
#     stub code, including this code)
# ============================================================================

# type: ignore

# <litgen_stub> // Autogenerated code below! Do not edit!
####################    <generated_from:namespace_test.h>    ####################

def foo_root() -> int:
    pass

# <submodule inner>
class inner:  # Proxy class that introduces typings for the *submodule* inner
    pass  # (This corresponds to a C++ namespace. All method are static!)
    """ this is an inner namespace (this comment should become the namespace doc)"""
    @staticmethod
    def foo_inner() -> int:
        pass
    @staticmethod
    def foo_inner2() -> int:
        pass

# </submodule inner>
####################    </generated_from:namespace_test.h>    ####################

# </litgen_stub> // Autogenerated code end!
