# <litgen_stub> // Autogenerated code below! Do not edit!
####################    <generated_from:inner_classes.h>    ####################
class Parent:
    a: int

    class Child:
        b: int
    child: Child

####################    </generated_from:inner_classes.h>    ####################

# </litgen_stub>
