# <litgen_stub> // Autogenerated code below! Do not edit!
####################    <generated_from:submodules.h>    ####################
# <Namespace Main>
class A:
    a: int

# </Namespace Main>
####################    </generated_from:submodules.h>    ####################

# </litgen_stub>
