import numpy as np

# <litgen_stub> // Autogenerated code below! Do not edit!
####################    <generated_from:BoxedTypes>    ####################
# <Autogenerated_Boxed_Types>
class BoxedFloat:
    value: float
    def __init__(self, v: float = 0.0) -> None:
        pass
    def __repr__(self) -> str:
        pass

# </Autogenerated_Boxed_Types>
####################    </generated_from:BoxedTypes>    ####################
####################    <generated_from:inner_classes.h>    ####################
class Parent:
    a: int = 1

    class Child:
        def __init__(self, _b: int = 0) -> None:
            pass
        b: int = 2
        def add(self, values_0: BoxedFloat, values_1: BoxedFloat, values_2: BoxedFloat) -> float:
            pass
    child: Child

    #    enum class Item
    #    {
    #        Zero = 0,
    #        One,
    #        Two
    #    };
    #    Item item;

####################    </generated_from:inner_classes.h>    ####################

# </litgen_stub>
