#include "litgensample.h"

#include <pybind11/pybind11.h>
#include <pybind11/numpy.h>
#include <stdint.h>

namespace py = pybind11;


void py_init_module_litgensample(py::module& m)
{
    using namespace LiterateGeneratorExample;

    // !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    // <autogen:pydef_cpp> // Autogenerated code below! Do not edit!

    // <namespace LiterateGeneratorExample>
    m.def("add",
        [](int a, int b)
        {
            return add(a, b);
        },
        py::arg("a"),
        py::arg("b"),
        "Adds two numbers"
    );

    m.def("add",
        [](int a, int b, int c)
        {
            return add(a, b, c);
        },
        py::arg("a"),
        py::arg("b"),
        py::arg("c"),
        "Adds three numbers, with a surprise"
    );

    m.def("add_inside_array",
        [](py::array & array, uint8_t number_to_add)
        {
            // convert array (py::array&) to C standard buffer (mutable)
            void* array_buffer = array.mutable_data();
            int array_count = array.shape()[0];
            
            char array_type = array.dtype().char_();
            if (array_type != 'B')
                throw std::runtime_error(std::string(R"msg(
                        Bad type!  Expected a buffer of native type:
                                    uint8_t *
                                Which is equivalent to 
                                    B
                                (using py::array::dtype().char_() as an id)
                    )msg"));

            add_inside_array(static_cast<uint8_t *>(array_buffer), array_count, number_to_add);
        },
        py::arg("array"),
        py::arg("number_to_add"),
        "Modify an array by adding a value to its elements (non template function)"
    );

    m.def("mul_inside_array",
        [](py::array & array, double factor)
        {
            // convert array (py::array&) to C standard buffer (mutable)
            void* array_buffer = array.mutable_data();
            int array_count = array.shape()[0];
            
            char array_type = array.dtype().char_();
            if (array_type == 'B')
                return mul_inside_array(static_cast<uint8_t*>(array_buffer), array_count, factor);
            else if (array_type == 'b')
                return mul_inside_array(static_cast<int8_t*>(array_buffer), array_count, factor);
            else if (array_type == 'H')
                return mul_inside_array(static_cast<uint16_t*>(array_buffer), array_count, factor);
            else if (array_type == 'h')
                return mul_inside_array(static_cast<int16_t*>(array_buffer), array_count, factor);
            else if (array_type == 'I')
                return mul_inside_array(static_cast<uint32_t*>(array_buffer), array_count, factor);
            else if (array_type == 'i')
                return mul_inside_array(static_cast<int32_t*>(array_buffer), array_count, factor);
            else if (array_type == 'L')
                return mul_inside_array(static_cast<uint64_t*>(array_buffer), array_count, factor);
            else if (array_type == 'l')
                return mul_inside_array(static_cast<int64_t*>(array_buffer), array_count, factor);
            else if (array_type == 'f')
                return mul_inside_array(static_cast<float*>(array_buffer), array_count, factor);
            else if (array_type == 'd')
                return mul_inside_array(static_cast<double*>(array_buffer), array_count, factor);
            else if (array_type == 'g')
                return mul_inside_array(static_cast<long double*>(array_buffer), array_count, factor);

            // If we reach this point, the array type is not supported!
            throw std::runtime_error(std::string("Bad array type: ") + array_type );
        },
        py::arg("array"),
        py::arg("factor"),
        "Modify an array by multiplying its elements (template function!)"
    );

    m.def("sub",
        [](int a, int b)
        {
            return sub(a, b);
        },
        py::arg("a"),
        py::arg("b")
    );

    m.def("mul",
        [](int a, int b)
        {
            return mul(a, b);
        },
        py::arg("a"),
        py::arg("b")
    );


    auto pyClassFoo = py::class_<Foo>
        (m, "Foo", "A superb struct\n\nMY_API_STRUCT")
        .def(py::init<>())
        .def_readwrite("factor", &Foo::factor, "Multiplication factor")
        .def_readwrite("delta", &Foo::delta, "addition factor")
        .def("calc",
            [](Foo & self, int x)
            {
                return self.calc(x);
            },
            py::arg("x"),
            "Do some math"
        )
        .def("instance",
            [](Foo & self)
            {
                return self.Instance();
            },
            "return_value_policy::reference",
            pybind11::return_value_policy::reference
        )
        ; 


    m.def("foo_instance",
        []()
        {
            return FooInstance();
        },
        "return_value_policy::reference",
        pybind11::return_value_policy::reference
    );

    // </namespace LiterateGeneratorExample>

    // </autogen:pydef_cpp> // Autogenerated code end
    // !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE END !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

}